/*
Created: 2/11/2022
Modified: 2/24/2022
Project: OHCDB
Model: OHCDB_RE
Company: Steampunk
Author: Kobi Lifshitz
Version: 2.0
Database: PostgreSQL 12
*/

set role :role;
set search_path to :schema;

-- Create tables section -------------------------------------------------

-- Table public.cxo_attrition_archive

CREATE TABLE "public"."cxo_attrition_archive"
(
  "PAY PERIOD" Text,
  "FY PP" Text,
  "TYPE" Text,
  "GAIN/LOSS" Text,
  "POSN NR" Text,
  "OFC" Text,
  "BUD" Text,
  "ORG" Text,
  "ORG TEXT" Text,
  "NAME" Text,
  "GRADE" Text,
  "STEP" Text,
  "PROG" Text,
  "FUND CODE" Text,
  "CAT CD" Text,
  "PROG ELEM" Text,
  "PROJ" Text,
  "PROJ TYPE" Text,
  "SERIES" Text,
  "TITLE" Text,
  "TITLE GROUP" Text,
  "PRIORITY" Text,
  "INCMB EOD DT" Text,
  "VACATE DT" Text,
  "NOAC" Text,
  "ENHANCE/SUPP YR" Text,
  "LEO" Text,
  "BWS" Text,
  "DIR" Text,
  "pp1" Text,
  "PAY PERIOD YEAR" Text,
  "ORG1" Text,
  "OFFICE" Text,
  "filename" Text,
  "cxo_pp1" Text,
  "cxo_fy" Text,
  "Annualization Factor" Text,
  "ingested_at" Timestamp with time zone,
  "SSN" Text
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_attrition_two_year_archive

CREATE TABLE "public"."cxo_attrition_two_year_archive"
(
  "PAY PERIOD" Bigint,
  "PP" Bigint,
  "FY" Bigint,
  "FY PP" Bigint,
  "TYPE" Bigint,
  "GAIN/LOSS" Text,
  "POSN NR" Bigint,
  "OFC" Text,
  "BUD" Text,
  "ORG" Text,
  "ORG TEXT" Text,
  "NAME" Text,
  "GRADE" Double precision,
  "STEP" Double precision,
  "PROG" Double precision,
  "FT" Text,
  "CAT CD" Text,
  "PROG ELEM" Double precision,
  "PROJ" Text,
  "PROJ TYPE" Text,
  "SERIES" Double precision,
  "TITLE" Text,
  "TITLE GROUP" Text,
  "PRIORITY" Text,
  "INCMB EOD DT" Double precision,
  "VACATE DT" Double precision,
  "NOAC" Double precision,
  "ENHANCE/SUPP YR" Text,
  "LEO" Text,
  "BWS" Double precision,
  "DIR" Text,
  "filename" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_cpro_archive_v2

CREATE TABLE "public"."cxo_cpro_archive_v2"
(
  "Pay Period End Date" Timestamp with time zone,
  "Person ID" Text,
  "Name" Text,
  "Sex Cd" Text,
  "RNO Cd" Text,
  "RNO cd nm" Text,
  "Handicap" Text,
  "Service Years" Text,
  "Age" Text,
  "Pay Plan" Text,
  "Grade" Text,
  "Step" Text,
  "Series" Text,
  "Title" Text,
  "Birth" Text,
  "BirthYear" Text,
  "Pos Supv Cd" Text,
  "WGI DATE" Timestamp with time zone,
  "SCD WGI YMD" Timestamp with time zone,
  "RET PGM" Text,
  "1st Eligibility Date Optional" Timestamp with time zone,
  "Duty City" Text,
  "Duty State_Abbr" Text,
  "Duty State" Text,
  "SCD LV" Text,
  "Residence State/Country Abbr" Text,
  "Veterans Preference RIF" Text,
  "Hourly Rate" Text,
  "Performance Evalunation Yr" Text,
  "Early Retirement Eligible Yr" Text,
  "Performance Evaluation Cd" Text,
  "Employment Status" Text,
  "Veterans Status" Text,
  "Entered Present Grade" Text,
  "1st Eligibility Date Early" Timestamp with time zone,
  "Optional Eligible Retirement Plan" Text,
  "Veterans Preference" Text,
  "Mandatory Eligible Retirement Yr" Text,
  "Optional Eligible Retirement Yr" Text,
  "Retirement Type & Plan Current" Text,
  "Retirement Eligibility Current" Text,
  "Series Name" Text,
  "FED Retirement Eligibility" Text,
  "EOD" Timestamp with time zone,
  "Pay Rate Determinant" Text,
  "Organization Cd" Text,
  "SCD CSR" Text,
  "LWOP Retirement RIF" Text,
  "DIR" Text,
  "OFFICE" Text,
  "BUD" Text,
  "ORG" Text,
  "ORG TEXT" Text,
  "POSN NR" Text,
  "FILLED/VACANT" Text,
  "INCMB/VICE NAME" Text,
  "FUND CODE" Text,
  "PROG" Text,
  "PRGE" Text,
  "PROJ" Text,
  "FUND PROG" Text,
  "CAT CD" Text,
  "FTEP" Text,
  "PP" Text,
  "SERIES" Text,
  "INCB GRD" Text,
  "PRFX" Text,
  "TITLE" Text,
  "MRN" Text,
  "PRIORITY" Text,
  "ENHANCE/SUPP YR" Text,
  "FUND IND" Text,
  "LAW ENF" Text,
  "SENS IND" Text,
  "BUS CD" Text,
  "GRP" Text,
  "HRS" Text,
  "DTL ORG CODE" Text,
  "EOD DT" Timestamp with time zone,
  "REL POS IND" Text,
  "REL POS NBR" Text,
  "NTE DT" Timestamp with time zone,
  "SF52" Text,
  "Selectee Name" Text,
  "ENTRY" Text,
  "FPL" Text,
  "DUTY CITY" Text,
  "DUTY STATE" Text,
  "NFC STORED ACCT" Text,
  "TOPS PAYROLL ACCT" Text,
  "TOPS IPAGUSE" Text,
  "CREATE ID" Text,
  "CREATE DT" Timestamp with time zone,
  "UPD ID" Text,
  "UPD DT" Text,
  "SCD DT" Text,
  "TITLE GROUP" Text,
  "DAYS VACANT" Text,
  "MCI" Text,
  "PROJ TYPE" Text,
  "BWS" Text,
  "CONUS" Text,
  "FLSA" Text,
  "HCO" Text,
  "SUPVY" Text,
  "DUTY LOC" Text,
  "CODE" Text,
  "SUFFIX" Text,
  "OFF/SUPRT" Text,
  "WORKING TITLE" Text,
  "CLASSF" Text,
  "CLASSF DT" Text,
  "LANG" Text,
  "RETIRE" Text,
  "INCMB PP" Text,
  "INCMB BASE" Text,
  "INCMB ADJ" Text,
  "DHS DT" Timestamp with time zone,
  "FED START DT" Timestamp with time zone,
  "INCMB GRADE DT" Text,
  "NOAC1" Text,
  "NOAC2" Text,
  "INCMB CAT CD" Text,
  "VAC RSN" Text,
  "VAC DT" Timestamp with time zone,
  "DAYS OCCUP" Text,
  "MAX NTE DT" Text,
  "INCMB NTE DT" Text,
  "AGENCY" Text,
  "SON" Text,
  "TOD HRS" Text,
  "FURLOUGH STATUS" Text,
  "HIRING ACTION" Text,
  "HIRING STATUS" Text,
  "CAS/PPA" Text,
  "CAS PPA DESCRIPTION" Text,
  "HQ/FIELD" Text,
  "PML on board" Text,
  "FISCAL YEAR" Text,
  "FY_PP" Text,
  "CY_PP" Text,
  "BARGAINING_UNIT_STATUS_CD" Bigint,
  "filename" Text,
  "cxo_pp1" Text,
  "cxo_fy" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_enhancement_archive

CREATE TABLE "public"."cxo_enhancement_archive"
(
  "Occ Series" Text,
  "EMPLOYEE_WORK_EMAIL" Text,
  "POSITION_OFFICIAL_TITLE" Text,
  "LEO_IND" Text,
  "SEX_CODE" Text,
  "filename" Text,
  "cxo_pp1" Text,
  "DIR" Text,
  "OFFICE" Text,
  "BUD" Text,
  "ORG" Text,
  "ORG TEXT" Text,
  "POSN NR" Text,
  "FILLED/VACANT" Text,
  "INCMB/VICE NAME" Text,
  "SERIES" Text,
  "STEP" Double precision,
  "TITLE" Text,
  "ENHANCE/SUPP YR" Text,
  "FUND IND" Text,
  "LAW ENF" Text,
  "EOD DT" Text,
  "REL POS IND" Text,
  "REL POS NBR" Text,
  "NTE DT" Text,
  "SF52" Text,
  "Selectee Name" Text,
  "FPL" Bigint,
  "DUTY CITY" Text,
  "DUTY STATE" Text,
  "TITLE GROUP" Text,
  "DAYS VACANT" Double precision,
  "DUTY LOC" Text,
  "CODE" Double precision,
  "SUFFIX" Text,
  "OFF/SUPRT" Text,
  "RETIRE" Text,
  "INCMB PP" Text,
  "INCMB BASE" Double precision,
  "INCMB ADJ" Double precision,
  "DHS DT" Text,
  "FED START DT" Text,
  "INCMB GRADE DT" Text,
  "NOAC1" Double precision,
  "NOAC2" Double precision,
  "INCMB CAT CD" Text,
  "VAC DT" Text,
  "DAYS OCCUP" Double precision,
  "MAX NTE DT" Text,
  "INCMB NTE DT" Double precision,
  "AGENCY" Text,
  "TOD HRS" Bigint,
  "HIRING ACTION" Text,
  "HIRING STATUS" Text,
  "CAS/PPA" Text,
  "CAS PPA DESCRIPTION" Text,
  "HQ/FIELD" Bigint,
  "PML on board" Text,
  "OE-Status" Text,
  "CXO_ENHANCE/SUPP YR" Text,
  "cxo_fy" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_eoy_archive

CREATE TABLE "public"."cxo_eoy_archive"
(
  "dir" Text,
  "office" Text,
  "bud" Text,
  "org" Text,
  "org text" Text,
  "posn nr" Text,
  "filled_vacant" Text,
  "incmb_vice name" Text,
  "ft" Text,
  "prog" Text,
  "prge" Text,
  "proj" Text,
  "fund prog" Text,
  "cat cd" Text,
  "ftep" Text,
  "pp" Text,
  "series" Text,
  "incb grd" Text,
  "step" Text,
  "prfx" Text,
  "title" Text,
  "mrn" Text,
  "priority" Text,
  "enhance_supp yr" Text,
  "fund_ind" Text,
  "law_enf" Text,
  "sens_ind" Text,
  "bus_cd" Text,
  "grp" Text,
  "hrs" Text,
  "dtl_org_code" Text,
  "eod_dt" Text,
  "rel_pos_ind" Text,
  "rel_pos_nbr" Text,
  "nte_dt" Text,
  "sf52" Text,
  "selectee_name" Text,
  "entry" Text,
  "fpl" Text,
  "DUTY CITY" Text,
  "DUTY STATE" Text,
  "nfc_stored_acct" Text,
  "tops_payroll_acct" Text,
  "tops_ipaguse" Text,
  "create_id" Text,
  "create_dt" Text,
  "upd_id" Text,
  "upd_dt" Text,
  "scd_dt" Text,
  "title_group" Text,
  "days_vacant" Text,
  "mci" Text,
  "proj_type" Text,
  "bws" Text,
  "conus" Text,
  "flsa" Text,
  "hco" Text,
  "supvy" Text,
  "duty_loc" Text,
  "code" Text,
  "suffix" Text,
  "off_suprt" Text,
  "working_title" Text,
  "classf" Text,
  "classf_dt" Text,
  "lang" Text,
  "retire" Text,
  "incmb_pp" Text,
  "incmb_base" Text,
  "incmb_adj" Text,
  "dhs_dt" Text,
  "fed_start_dt" Text,
  "incmb_grade_dt" Text,
  "noac1" Text,
  "noac2" Text,
  "incmb_cat_cd" Text,
  "vac_rsn" Text,
  "vac_dt" Text,
  "days_occup" Text,
  "max_nte_dt" Text,
  "incmb_nte_dt" Text,
  "agency" Text,
  "son" Text,
  "tod_hrs" Text,
  "furlough_status" Text,
  "hiring_action" Text,
  "hiring_status" Text,
  "cas_ppa" Text,
  "cas_ppa_description" Text,
  "hq_field" Text,
  "pml_on_board" Text,
  "fiscal_year" Text,
  "fy_pp" Text,
  "cy_pp" Text,
  "Org Structure" Text,
  "POI" Text,
  "Pay Plan" Text,
  "Occ Series" Text,
  "Grade/Step" Text,
  "Employee Name" Text,
  "Type of Appointment" Text,
  "Duty Station" Text,
  "Base Contract Salary" Text,
  "Age" Text,
  "EMPLOYEE_WORK_EMAIL" Text,
  "ANNUITANT_INDICATOR" Text,
  "DATE_AGENCY_EOD" Timestamp with time zone,
  "DATE_ENTERED_POI" Text,
  "DATE_OF_BIRTH" Timestamp with time zone,
  "DATE_SCD_WGI" Timestamp with time zone,
  "FAIR_LABOR_STANDARDS_CODE" Text,
  "GRADE" Text,
  "MASTER_RECORD_NUMBER" Text,
  "POSITION_NUMBER" Text,
  "POSITION_OFFICIAL_TITLE" Text,
  "POSITION_SUPERVISORY_CODE" Text,
  "SPEC_EMPLOYMENT_PGMS_CODE" Text,
  "SPECIAL_EMPLOYEE_CODE" Text,
  "TENURE_GROUP" Text,
  "WORK_SCHEDULE" Text,
  "DATE_ENTERED_PRES_GRADE" Text,
  "DATE_NON_PAY_NTE" Text,
  "PMSO_IP_AGY_USE" Text,
  "POSITION_TARGET_GRADE" Text,
  "DATE_6C_RETIREMENT" Text,
  "DATE_CBPO_RET_SCD" Text,
  "DATE_SCD_CSR" Text,
  "DATE_SCD_LEAVE" Text,
  "RT_PLAN_CODE" Text,
  "DATE_CAREER_PERM_TEN_START" Text,
  "DATE_PROB_PERIOD_START" Text,
  "LEO_IND" Text,
  "UNIFORM_SERVICE_STATUS" Text,
  "BARGAINING_UNIT_STATUS_CD" Text,
  "DATE_DETL_EXPIR" Timestamp with time zone,
  "DATE_PROMOTION_NTE" Timestamp with time zone,
  "SCHEDULED_SALARY" Text,
  "SEX_CODE" Text,
  "PREVIOUS_AGENCY_CODE" Text,
  "POSITION_STATUS_CODE" Text,
  "filename" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_esp_archive_v2

CREATE TABLE "public"."cxo_esp_archive_v2"
(
  "request_number" Text,
  "DIRECTORATE_CODE1" Text,
  "office_code" Text,
  "bud_loc_code" Text,
  "DUTY_LOC_CODE" Text,
  "duty_city" Text,
  "duty_county" Text,
  "duty_state" Text,
  "ppa" Text,
  "location" Text,
  "phase" Text,
  "stage" Text,
  "staffing_type" Text,
  "int_ext" Text,
  "first_name" Text,
  "last_name" Text,
  "master" Text,
  "group_name" Text,
  "create_date" Text,
  "title" Text,
  "grade" Text,
  "series" Text,
  "request_code" Text,
  "request_code_description" Text,
  "process" Text,
  "org_code" Text,
  "line1" Text,
  "line2" Text,
  "line3" Text,
  "line4" Text,
  "line5" Text,
  "line6" Text,
  "line7" Text,
  "line8" Text,
  "HQ" Text,
  "ip_no" Text,
  "enhancement" Text,
  "priority" Text,
  "project_code" Text,
  "announcement_code" Text,
  "certificate_name" Text,
  "announcement_owner" Text,
  "box_type" Text,
  "eff_date" Text,
  "FY" Text,
  "PP" Text,
  "use" Text,
  "eff_date_2" Text,
  "proposed_effective_date" Text,
  "gid" Text,
  "unique_id" Text,
  "internal_selection" Text,
  "leo_code" Text,
  "title_group_code" Text,
  "cxo_pp1" Text,
  "cxo_fy" Text,
  "filename" Text,
  "ingested_at" Timestamp with time zone,
  "pp_end" Text,
  "cxo_pp2" Text,
  "cxo_fy2" Text
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_fevs_archive

CREATE TABLE "public"."cxo_fevs_archive"
(
  "2020 Agency And Subagency Name" Text,
  "DIR" Text,
  "OFFICE" Text,
  "BUD" Text,
  "ORG" Text,
  "ORG TEXT" Text,
  "Level Code" Text,
  "Level" Text,
  "Employee Engagement Overall" Double precision,
  "filename" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_mco_archive

CREATE TABLE "public"."cxo_mco_archive"
(
  "TITLE GROUP" Text,
  "PML" Double precision,
  "FY20 Target" Double precision,
  "To Goal" Double precision,
  "Fill Rate Percent" Double precision,
  "Fill Rate Target" Double precision,
  "filename" Text,
  "cxo_fy" Text,
  "cxo_pp1" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_nfc_tops_archive_v4

CREATE TABLE "public"."cxo_nfc_tops_archive_v4"
(
  "Org Structure" Text,
  "POI" Text,
  "Pay Plan" Text,
  "Occ Series" Text,
  "Grade/Step" Text,
  "Employee Name" Text,
  "Type of Appointment" Text,
  "Duty Station" Text,
  "Base Contract Salary" Text,
  "Age" Text,
  "EMPLOYEE_WORK_EMAIL" Text,
  "ANNUITANT_INDICATOR" Text,
  "DATE_AGENCY_EOD" Timestamp with time zone,
  "DATE_ENTERED_POI" Timestamp with time zone,
  "DATE_OF_BIRTH" Timestamp with time zone,
  "DATE_SCD_WGI" Timestamp with time zone,
  "FAIR_LABOR_STANDARDS_CODE" Text,
  "GRADE" Text,
  "MASTER_RECORD_NUMBER" Text,
  "POSITION_NUMBER" Text,
  "POSITION_OFFICIAL_TITLE" Text,
  "POSITION_SUPERVISORY_CODE" Text,
  "SPEC_EMPLOYMENT_PGMS_CODE" Text,
  "SPECIAL_EMPLOYEE_CODE" Text,
  "STEP_x" Text,
  "TENURE_GROUP" Text,
  "WORK_SCHEDULE" Text,
  "DATE_ENTERED_PRES_GRADE" Timestamp with time zone,
  "DATE_NON_PAY_NTE" Timestamp with time zone,
  "PMSO_IP_AGY_USE" Text,
  "POSITION_TARGET_GRADE" Text,
  "DATE_6C_RETIREMENT" Timestamp with time zone,
  "DATE_CBPO_RET_SCD" Timestamp with time zone,
  "DATE_SCD_CSR" Timestamp with time zone,
  "DATE_SCD_LEAVE" Timestamp with time zone,
  "RT_PLAN_CODE" Text,
  "DATE_CAREER_PERM_TEN_START" Timestamp with time zone,
  "DATE_PROB_PERIOD_START" Timestamp with time zone,
  "LEO_IND" Text,
  "UNIFORM_SERVICE_STATUS" Text,
  "BARGAINING_UNIT_STATUS_CD" Text,
  "DATE_DETL_EXPIR" Timestamp with time zone,
  "DATE_PROMOTION_NTE" Timestamp with time zone,
  "SCHEDULED_SALARY" Text,
  "SEX_CODE" Text,
  "PREVIOUS_AGENCY_CODE" Text,
  "POSITION_STATUS_CODE" Text,
  "filename" Text,
  "cxo_pp1" Text,
  "cxo_org_structure" Text,
  "DIR" Text,
  "OFFICE" Text,
  "BUD" Text,
  "ORG" Text,
  "ORG TEXT" Text,
  "POSN NR" Text,
  "FILLED/VACANT" Text,
  "INCMB/VICE NAME" Text,
  "FUND CODE" Text,
  "PROG" Text,
  "PRGE" Text,
  "PROJ" Text,
  "FUND PROG" Text,
  "CAT CD" Text,
  "FTEP" Text,
  "PP" Text,
  "SERIES" Text,
  "INCB GRD" Text,
  "STEP_y" Text,
  "PRFX" Text,
  "TITLE" Text,
  "MRN" Text,
  "PRIORITY" Text,
  "ENHANCE/SUPP YR" Text,
  "FUND IND" Text,
  "LAW ENF" Text,
  "SENS IND" Text,
  "BUS CD" Text,
  "GRP" Text,
  "HRS" Text,
  "DTL ORG CODE" Text,
  "EOD DT" Text,
  "REL POS IND" Text,
  "REL POS NBR" Text,
  "NTE DT" Text,
  "SF52" Text,
  "Selectee Name" Text,
  "ENTRY" Text,
  "FPL" Text,
  "DUTY CITY" Text,
  "DUTY STATE" Text,
  "NFC STORED ACCT" Text,
  "TOPS PAYROLL ACCT" Text,
  "TOPS IPAGUSE" Text,
  "CREATE ID" Text,
  "CREATE DT" Text,
  "UPD ID" Text,
  "UPD DT" Text,
  "SCD DT" Text,
  "TITLE GROUP" Text,
  "DAYS VACANT" Text,
  "MCI" Text,
  "PROJ TYPE" Text,
  "BWS" Text,
  "CONUS" Text,
  "FLSA" Text,
  "HCO" Text,
  "SUPVY" Text,
  "DUTY LOC" Text,
  "CODE" Text,
  "SUFFIX" Text,
  "OFF/SUPRT" Text,
  "WORKING TITLE" Text,
  "CLASSF" Text,
  "CLASSF DT" Text,
  "LANG" Text,
  "RETIRE" Text,
  "INCMB PP" Text,
  "INCMB BASE" Text,
  "INCMB ADJ" Text,
  "DHS DT" Text,
  "FED START DT" Text,
  "INCMB GRADE DT" Text,
  "NOAC1" Text,
  "NOAC2" Text,
  "INCMB CAT CD" Text,
  "VAC RSN" Text,
  "VAC DT" Timestamp with time zone,
  "DAYS OCCUP" Text,
  "MAX NTE DT" Text,
  "INCMB NTE DT" Text,
  "AGENCY" Text,
  "SON" Text,
  "TOD HRS" Text,
  "FURLOUGH STATUS" Text,
  "HIRING ACTION" Text,
  "HIRING STATUS" Text,
  "CAS/PPA" Text,
  "CAS PPA DESCRIPTION" Text,
  "HQ/FIELD" Text,
  "PML on board" Text,
  "FISCAL YEAR" Text,
  "FY_PP" Text,
  "CY_PP" Text,
  "WGI DATE" Timestamp with time zone,
  "1st Eligibility Date Optional" Text,
  "Performance Evaluation Cd" Text,
  "Veterans Preference" Text,
  "Retirement Eligibility Current" Text,
  "cxo_fy" Text,
  "ingested_at" Timestamp with time zone,
  "pp_dt_end" Timestamp with time zone,
  "next_pp_dt" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_pml_archive

CREATE TABLE "public"."cxo_pml_archive"
(
  "dir" Text,
  "pml_office" Text,
  "full_time_permanent_positions_FTP" Double precision,
  "previous_fy_total_authorized" Double precision,
  "current_fy_total_authorized" Double precision,
  "287g_funded" Double precision,
  "working_capital_funded_IAAs" Double precision,
  "SEVP_funded" Double precision,
  "Puerto_Rico_Trust_Fund" Double precision,
  "Asset_Forfeiture_Funded" Double precision,
  "SLA_MOU_Pending_Review" Double precision,
  "PML_Total" Double precision,
  "SLA_MOU_Reconciled_as_of_end_of_fy_pp" Double precision,
  "blank" Double precision,
  "onboard_as_of_curr_pp" Double precision,
  "vacant_as_of_current_pp" Double precision,
  "on_board_other_than_FTP_as_of_cur_pp" Double precision,
  "total_on_board_count_as_of_curr_pp" Double precision,
  "previous_fy_enhancement_positions_onboard" Double precision,
  "previous_fy_enhancement_positions_vacant" Double precision,
  "curr_fy_enhancement_positions_onboard" Double precision,
  "curr_fy_enhancement_positions_vacant" Double precision,
  "filename" Text,
  "cxo_fy" Bigint,
  "cxo_pp1" Bigint,
  "ingest_at" Timestamp with time zone,
  "ingested_at" Timestamp with time zone,
  "previous_previous_fy_total_authorized" Double precision,
  "previous_previous_fy_enhancement_positions_onboard" Double precision,
  "previous_previous_fy_enhancement_positions_onboard" Double precision
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_population_archive

CREATE TABLE "public"."cxo_population_archive"
(
  "End of PP Date" Timestamp with time zone,
  "Pay Period #" Text,
  "Pay Period Order" Text,
  "Status" Text,
  "Onboard" Text
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_t2h_archive

CREATE TABLE "public"."cxo_t2h_archive"
(
  "PAY PERIOD" Text,
  "GAIN/LOSS" Text,
  "OFC" Text,
  "BUD" Text,
  "ORG" Text,
  "ORG TEXT" Text,
  "NAME" Text,
  "GRADE" Bigint,
  "CAT CD" Text,
  "SERIES" Bigint,
  "TITLE" Text,
  "TITLE GROUP" Text,
  "INCMB EOD DT" Text,
  "LEO" Text,
  "DIR" Text,
  "Touch Point" Bigint,
  "SF-52 Number" Text,
  "Need Validated" Timestamp with time zone,
  "SF-52 Date" Timestamp with time zone,
  "Days" Bigint,
  "SF-52 Received Date" Timestamp with time zone,
  "PD Reviewed" Timestamp with time zone,
  "Days.1" Double precision,
  "PD Reviewed.1" Timestamp with time zone,
  "Job Analysis End Date" Timestamp with time zone,
  "Days.2" Double precision,
  "Job ANAlysis End Date" Timestamp with time zone,
  "Anncmt Open Date" Text,
  "Days.3" Double precision,
  "Anncmt Open Date.1" Text,
  "Anncmt Closed Date" Text,
  "Days.4" Text,
  "Anncmt Closed Date.1" Text,
  "Days.5" Text,
  "Evaluate Applications" Text,
  "Evaluate Applications.1" Text,
  "Days.6" Text,
  "Certifiate Issued Date" Text,
  "Days.7" Text,
  "Certifiate Issued Date.1" Text,
  "Cert Returned Date" Text,
  "Days.8" Text,
  "Cert Returned Date.1" Text,
  "Tentative Job Offer Date" Timestamp with time zone,
  "Days.9" Text,
  "Tentative Job Offer Date.1" Timestamp with time zone,
  "PSU Inquiry" Text,
  "Days.10" Text,
  "Final PSU" Text,
  "Official Offer Date" Timestamp with time zone,
  "Days.11" Text,
  "Official Offer Date.1" Timestamp with time zone,
  "EOD DT" Timestamp with time zone,
  "T2H" Bigint,
  "EOD-TJO" Double precision,
  "EOD-OJO" Double precision,
  "T2h Need to TJO" Bigint,
  "filename" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.refresh_table_d1

CREATE TABLE "public"."refresh_table_d1"
(
  "table_name" Text,
  "updated" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.performance_crosswalk

CREATE TABLE "public"."performance_crosswalk"
(
  "Performance Evaluation Cd" Text,
  "numeric_grouping" Bigint,
  "performance_evaluation_cd_tableau" Text
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.quarter_mapping_tb

CREATE TABLE "public"."quarter_mapping_tb"
(
  "cxo_qtr" Text,
  "cxo_pp1_group" Text
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_esp_actions_archive

CREATE TABLE "public"."cxo_esp_actions_archive"
(
  "DIR" Text,
  "PROGRAM_OFFICE" Text,
  "BUD_LOC" Text,
  "IPN" Text,
  "ENHANCEMENT" Text,
  "PRIORITY" Text,
  "PROJECT_CODE" Text,
  "FIRST_NAME" Text,
  "LAST_NAME" Text,
  "MRN" Text,
  "TITLE" Text,
  "GRADE" Text,
  "SERIES" Text,
  "REQUEST_NUMBER" Text,
  "REQUEST_CODE" Text,
  "DESCRIPTION" Text,
  "GRP_NAME" Text,
  "GROUP_TYPE" Text,
  "ORG_CODE" Text,
  "LINE1" Text,
  "LINE2" Text,
  "LINE3" Text,
  "LINE4" Text,
  "LINE5" Text,
  "LINE6" Text,
  "BOX_TYPE" Text,
  "EFFECTIVE_DATE" Text,
  "INTERNAL_SELECTION" Text,
  "POI" Text,
  "DATE_CREATED" Text,
  "LAST_ACTIVITY" Text,
  "ANNOUNCEMENT_CODE" Text,
  "CERTIFICATE_NAME" Text,
  "ANNOUNCEMENT_OWNER" Text,
  "CATEGORY_CODE" Text,
  "filename" Text,
  "cxo_pp1" Text,
  "fy" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_esp_awards_archive

CREATE TABLE "public"."cxo_esp_awards_archive"
(
  "REQUEST NUMBER" Text,
  "NOA" Text,
  "DESCRIPTION" Text,
  "TIME OFF HOURS" Text,
  "AWARD AMOUNT" Text,
  "USE STORED ACCT" Text,
  "ACCTG_DIST_CODE" Text,
  "CREATOR GROUP" Text,
  "CURRENT GROUP" Text,
  "PEFF DATE" Text,
  "EFFECTIVE DATE" Text,
  "FULL NAME" Text,
  "POS TITLE" Text,
  "SERIES" Text,
  "GRADE" Text,
  "STEP" Text,
  "ORG" Text,
  "LINE1" Text,
  "LINE2" Text,
  "LINE3" Text,
  "LINE4" Text,
  "LINE5" Text,
  "ORGANIZATION" Text,
  "DEPT" Text,
  "STATUS" Text,
  "OPEN DATE" Text,
  "CLOSE DATE" Text,
  "GROUP AWARD" Text,
  "GROUP COUNT" Text,
  "TIME OFF" Text,
  "PERS ACTN DATE" Text,
  "PERIOD COVERED START DATE" Text,
  "PERIOD COVERED END DATE" Text,
  "ACCESS CODE" Text,
  "filename" Text,
  "pp_end" Timestamp with time zone,
  "cxo_pp1" Text,
  "cxo_fy" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_nfc_rno_archive

CREATE TABLE "public"."cxo_nfc_rno_archive"
(
  "Pay Period End Date" Text,
  "Person ID" Text,
  "Name" Text,
  "Sex Cd" Text,
  "RNO Cd" Text,
  "RNO cd nm" Text,
  "Handicap" Text,
  "Service Years" Text,
  "Age_x" Text,
  "Pay Plan" Text,
  "Grade" Text,
  "Step" Text,
  "Series" Text,
  "Title" Text,
  "Birth" Text,
  "BirthYear" Text,
  "Pos Supv Cd" Text,
  "WGI DATE" Text,
  "SCD WGI YMD" Text,
  "RET PGM" Text,
  "1st Eligibility Date Optional" Text,
  "Duty City" Text,
  "Duty State_Abbr" Text,
  "Duty State" Text,
  "SCD LV" Text,
  "Residence State/Country Abbr" Text,
  "Veterans Preference RIF" Text,
  "Hourly Rate" Text,
  "Performance Evalunation Yr" Text,
  "Early Retirement Eligible Yr" Text,
  "Performance Evaluation Cd" Text,
  "Employment Status" Text,
  "Veterans Status" Text,
  "Entered Present Grade" Text,
  "1st Eligibility Date Early" Text,
  "Optional Eligible Retirement Plan" Text,
  "Veterans Preference" Text,
  "Mandatory Eligible Retirement Yr" Text,
  "Optional Eligible Retirement Yr" Text,
  "Retirement Type & Plan Current" Text,
  "Retirement Eligibility Current" Text,
  "Series Name" Text,
  "FED Retirement Eligibility" Text,
  "EOD" Text,
  "Pay Rate Determinant" Text,
  "Organization Cd" Text,
  "SCD CSR" Text,
  "LWOP Retirement RIF" Text,
  "DIR" Text,
  "OFFICE" Text,
  "BUD" Text,
  "ORG" Text,
  "ORG TEXT" Text,
  "POSN NR" Text,
  "FILLED/VACANT" Text,
  "INCMB/VICE NAME" Text,
  "FUND CODE" Text,
  "PROG" Text,
  "PRGE" Text,
  "PROJ" Text,
  "FUND PROG" Text,
  "CAT CD" Text,
  "FTEP" Text,
  "PP" Text,
  "SERIES_x" Text,
  "INCB GRD" Text,
  "PRFX" Text,
  "TITLE" Text,
  "MRN" Text,
  "PRIORITY" Text,
  "ENHANCE/SUPP YR" Text,
  "FUND IND" Text,
  "LAW ENF" Text,
  "SENS IND" Text,
  "BUS CD" Text,
  "GRP" Text,
  "HRS" Text,
  "DTL ORG CODE" Text,
  "EOD DT" Text,
  "REL POS IND" Text,
  "REL POS NBR" Text,
  "NTE DT" Text,
  "SF52" Text,
  "Selectee Name" Text,
  "ENTRY" Text,
  "FPL" Text,
  "DUTY CITY" Text,
  "DUTY STATE" Text,
  "NFC STORED ACCT" Text,
  "TOPS PAYROLL ACCT" Text,
  "TOPS IPAGUSE" Text,
  "CREATE ID" Text,
  "CREATE DT" Text,
  "UPD ID" Text,
  "UPD DT" Text,
  "SCD DT" Text,
  "TITLE GROUP" Text,
  "DAYS VACANT" Text,
  "MCI" Text,
  "PROJ TYPE" Text,
  "BWS" Text,
  "CONUS" Text,
  "FLSA" Text,
  "HCO" Text,
  "SUPVY" Text,
  "DUTY LOC" Text,
  "CODE" Text,
  "SUFFIX" Text,
  "OFF/SUPRT" Text,
  "WORKING TITLE" Text,
  "CLASSF" Text,
  "CLASSF DT" Text,
  "LANG" Text,
  "RETIRE" Text,
  "INCMB PP" Text,
  "INCMB BASE" Text,
  "INCMB ADJ" Text,
  "DHS DT" Text,
  "FED START DT" Text,
  "INCMB GRADE DT" Text,
  "NOAC1" Text,
  "NOAC2" Text,
  "INCMB CAT CD" Text,
  "VAC RSN" Text,
  "VAC DT" Text,
  "DAYS OCCUP" Text,
  "MAX NTE DT" Text,
  "INCMB NTE DT" Text,
  "AGENCY" Text,
  "SON" Text,
  "TOD HRS" Text,
  "FURLOUGH STATUS" Text,
  "HIRING ACTION" Text,
  "HIRING STATUS" Text,
  "CAS/PPA" Text,
  "CAS PPA DESCRIPTION" Text,
  "HQ/FIELD" Text,
  "PML on board" Text,
  "FISCAL YEAR" Text,
  "FY_PP" Text,
  "CY_PP" Text,
  "BARGAINING_UNIT_STATUS_CD" Text,
  "POI" Text,
  "NAME" Text,
  "PAY_PLAN" Text,
  "SERIES_y" Text,
  "GRADE" Text,
  "OFFICIAL_TITLE" Text,
  "ORG_CODE" Text,
  "DATE_OF_BIRTH" Text,
  "Age_y" Text,
  "Age_Group" Text,
  "Gender" Text,
  "Census Race" Text,
  "OPM Race" Text,
  "Full Race" Text,
  "Disability_Code_and_Descr" Text,
  "VETERAN_PREF_CODE" Text,
  "Veteran_Pref_Code_Descr" Text,
  "Veteran_Pref_Group" Text,
  "VETERAN_STATUS_CODE" Text,
  "Veteran_Status_Descr" Text,
  "Veteran_Status_Group" Text,
  "VETERAN_PREF_RIF" Text,
  "UNIFORM_SERVICE_STATUS" Text,
  "METRO DC" Text,
  "RNO_CODE" Text,
  "RNO_Code_Descr" Text,
  "RNO_ERI_CONVERSION" Text,
  "ERI_Code" Text,
  "ORG_CODE_LEVEL_2" Text,
  "ORG_CODE_LEVEL_2_DESCR" Text,
  "ORG_CODE_LEVEL_3" Text,
  "ORG_CODE_LEVEL_3_DESCR" Text,
  "ORG_CODE_LEVEL_4" Text,
  "ORG_CODE_LEVEL_4_DESCR" Text,
  "ORG_CODE_LEVEL_5" Text,
  "ORG_CODE_LEVEL_5_DESCR" Text,
  "ORG_CODE_LEVEL_6" Text,
  "ORG_CODE_LEVEL_6_DESCR" Text,
  "CITY_CODE" Text,
  "CITY_NAME" Text,
  "COUNTY_CODE" Text,
  "COUNTY_NAME" Text,
  "STATE_CODE" Text,
  "STATE_NAME" Text,
  "filename" Text,
  "cxo_pp1" Text,
  "cxo_fy" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_noa_archive_v2

CREATE TABLE "public"."cxo_noa_archive_v2"
(
  "PrsnID" Text,
  "Last Name" Text,
  "First Name" Text,
  "Middle Name" Text,
  "Sex Cd" Text,
  "Rno Cd" Text,
  "Longtitle" Text,
  "Dept Cd" Text,
  "Org" Text,
  "Pay Plan" Text,
  "Grade" Text,
  "Step" Text,
  "Series" Text,
  "Pos Off Ttl" Text,
  "Type Apnt" Text,
  "Type Emp" Text,
  "Mr No" Text,
  "Pos No" Text,
  "Dty Hrs" Text,
  "Duty" Text,
  "Bus" Text,
  "Pos Spvs Cd" Text,
  "Leo Ind" Text,
  "Off Ttl Cd" Text,
  "Vet Pref Rif" Text,
  "Vet Pref Cd" Text,
  "Emp Status" Text,
  "Salary Rt" Text,
  "NOA Cd" Text,
  "NOA Description" Text,
  "Csc Auth 12" Text,
  "Csc Auth 22" Text,
  "NOA Dt" Text,
  "Apnt Na Actn" Text,
  "Apnt Auth 1" Text,
  "Apnt Auth 2" Text,
  "Apnt Ymd" Text,
  "Pp Nbr" Text,
  "Pp Ymd" Text,
  "Lt 063 Ida" Text,
  "Valid Ymd" Text,
  "BirthDt" Text,
  "Agcy Eod" Text,
  "NTE" Text,
  "Apnt Cd" Text,
  "Ga Lo N Usda" Text,
  "Geo Adj Pct" Text,
  "Actn Cd" Text,
  "Poi" Text,
  "Prog Cd" Text,
  "Award Amount" Text,
  "filename" Text,
  "cxo_pp1" Text,
  "cxo_fy" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_tops_605_error_archive

CREATE TABLE "public"."cxo_tops_605_error_archive"
(
  "OFC" Text,
  "BUD" Text,
  "ORG" Text,
  "ORG TEXT" Text,
  "POSN NR" Text,
  "ERR NBR" Text,
  "ERR MSG" Text,
  "PAY PERIOD" Text,
  "IPKEY" Text,
  "NFC MRN" Text,
  "NFC NAME" Text,
  "NFC PREFIX" Text,
  "NFC TITLE CD" Text,
  "NFC SUFFIX" Text,
  "NFC TITLE" Text,
  "NFC SERIES" Text,
  "NFC FUND CODE" Text,
  "NFC PROG" Text,
  "NFC PROJ" Text,
  "NFC CAT CD" Text,
  "NFC DUTY" Text,
  "NFC GRADE" Text,
  "NFC FPL" Text,
  "NFC ORG CD" Text,
  "NFC IPAGUSE" Text,
  "TOPS MRN" Text,
  "TOPS NAME" Text,
  "TOPS PREFIX" Text,
  "TOPS TITLE CD" Text,
  "TOPS SUFFIX" Text,
  "TOPS TITLE" Text,
  "TOPS SERIES" Text,
  "TOPS FUND CODE" Text,
  "TOPS PROG" Text,
  "TOPS PROJ" Text,
  "TOPS CAT" Text,
  "TOPS DUTY" Text,
  "TOPS EL" Text,
  "TOPS FPL" Text,
  "TOPS ORG CD" Text,
  "TOPS IPAGUSE" Text,
  "ERR PAY" Text,
  "DIR" Text,
  "LAW ENF" Text,
  "PML on board" Text,
  "FISCAL YEAR" Text,
  "CY_PP" Text,
  "filename" Text,
  "cxo_fy" Text,
  "cxo_pp1" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_tops_606_error_archive

CREATE TABLE "public"."cxo_tops_606_error_archive"
(
  "OFC" Text,
  "BUD" Text,
  "ORG" Text,
  "ORG TEXT" Text,
  "POSN NR" Text,
  "ERR MSG" Text,
  "PAY PERIOD" Text,
  "IPKEY" Text,
  "NFC MRN" Text,
  "NFC NAME" Text,
  "NFC PREFIX" Text,
  "NFC TITLE CD" Text,
  "NFC SUFFIX" Text,
  "NFC TITLE" Text,
  "NFC SERIES" Text,
  "NFC FUND CODE" Text,
  "NFC PROG" Text,
  "NFC PROJ" Text,
  "NFC CAT CD" Text,
  "NFC DUTY" Text,
  "NFC GRADE" Text,
  "NFC FPL" Text,
  "NFC ORG CD" Text,
  "NFC IPAGUSE" Text,
  "TOPS MRN" Text,
  "TOPS NAME" Text,
  "TOPS PREFIX" Text,
  "TOPS TITLE CD" Text,
  "TOPS SUFFIX" Text,
  "TOPS TITLE" Text,
  "TOPS SERIES" Text,
  "TOPS FUND CODE" Text,
  "TOPS PROG" Text,
  "TOPS PROJ" Text,
  "TOPS CAT" Text,
  "TOPS DUTY" Text,
  "TOPS EL" Text,
  "TOPS FPL" Text,
  "TOPS ORG CD" Text,
  "TOPS IPAGUSE" Text,
  "ERR PAY" Bigint,
  "DIR" Text,
  "LAW ENF" Text,
  "PML on board" Text,
  "FISCAL YEAR" Text,
  "CY_PP" Text,
  "filename" Text,
  "cxo_fy" Text,
  "cxo_pp1" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_usa1_archive

CREATE TABLE "public"."cxo_usa1_archive"
(
  "Certificate Vacancy Staffing Office Name" Text,
  "Certificate Vacancy Customer Agency Reference Code" Text,
  "Certificate Announcement Open Date" Text,
  "Certificate Vacancy Number" Text,
  "Certificate Number" Text,
  "Certificate Vacancy Series Title" Text,
  "Certificate Vacancy Series" Text,
  "Certificate Request Description" Text,
  "filename" Text,
  "cxo_fy" Text,
  "cxo_pp1" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.cxo_usa2_archive

CREATE TABLE "public"."cxo_usa2_archive"
(
  "Vacancy Number" Text,
  "Vacancy Total Applicants" Text,
  "Vacancy Total Selected Applicants" Text,
  "filename" Text,
  "cxo_fy" Text,
  "cxo_pp1" Text,
  "ingested_at" Timestamp with time zone
)
WITH (
  autovacuum_enabled=true)
;

-- Table public.thermometer_chart_path

CREATE TABLE "public"."thermometer_chart_path"
(
  "path" Character varying(255)
)
WITH (
  autovacuum_enabled=true)
;

-- Grant permissions section -------------------------------------------------


